# Generated automatically from Makefile.in by configure.
# Makefile for conquest - generated by configure from Makefile.in
#
#
# Jon Trulson
#
# $Id$
#
###########################################################################

# User defineable options
CONQBIN = /opt/bin
CONQHOME = /opt/conquest


# Unixware: try -Ki486 or -Kpentium -
#  might improve performance depending on processor type.
#LCFLAGS = -Kpentium
LCFLAGS = -Kpentium


CFLAGS =  -O -Xa -DHAVE_CONFIG_H $(LCFLAGS) -DCONQHOME=\"$(CONQHOME)\"
CONQUEST = conquest
CONQAI = conqai
CONQOPER = conqoper
CONQDRIV = conqdriv
CONQSTRAT = conqstrat

# The documentation
CONQHELP = conquest.doc
CONQNEWS = conqnews.doc

CURDIR=.
CONQC = conqfig.c ratfor.c cd2lb.c ionlb.c ioxlb.c \
	conqlb.c gamlb.c ioplb.c rndlb.c conqmisc.c conqutil.c conqcm.c \
	conqsvr42.c global.c ibuf.c version.c conf.c sem.c

CONQOBJS = conqfig.o ratfor.o cd2lb.o ionlb.o ioxlb.o \
	conqlb.o gamlb.o ioplb.o rndlb.o conqmisc.o conqutil.o conqcm.o \
	conqsvr42.o global.o ibuf.o version.o conf.o sem.o

# For installation
BCONQUEST = $(CONQHOME)/bin/conquest
BCONQOPER = $(CONQHOME)/bin/conqoper
BCONQDRIV = $(CONQHOME)/bin/conqdriv
BCONQAI = $(CONQHOME)/bin/conqai
BCONQSTRAT = $(CONQHOME)/bin/conqstrat
HCONQHELP = $(CONQHOME)/etc/$(CONQHELP)
HCONQNEWS = $(CONQHOME)/etc/$(CONQNEWS)

CONQLB = libconquest.so

EXTLBS = -lcurses -lm  -ll -ly

LEX = lex
YACC = yacc

# [shared|static] lib build options
LBFLAGS =  -G $(CFLAGS) -o $(CONQLB)

# End of config options - No user servicable parts inside.
default:
	@echo "type gmake <target>, where <target> is:"
	@echo ""
	@echo "all	- make all the binaries"
	@echo "install	- to install the binaries (must be root)"
	@echo "clean	- to remove all .o's, libs, and binaries"
	@echo "depend	- to make a dependancy list for your makefile."
	@echo "           Use 'gmake clean' before building if you are"
	@echo "           lacking a 'makedepend' command."

all: $(CONQLB) $(CONQUEST) $(CONQOPER) $(CONQAI) $(CONQDRIV) $(CONQSTRAT)

# program building  
##################

conquest: conquest.o 
	@-rm -f conquest
	$(CC) -o conquest $(CFLAGS) conquest.o $(CURDIR)/$(CONQLB) $(EXTLBS)
	@chgrp conquest conquest
	@chmod 2771 conquest

conquest.o: conquest.c c_defs.h defs.h conqdef.h conqcom.h conqcom2.h
	$(CC) $(CFLAGS) -c conquest.c

conqdriv.o: conqdriv.c c_defs.h defs.h conqdef.h conqcom.h conqcom2.h
	$(CC) $(CFLAGS) -c conqdriv.c

conqdriv: conqdriv.o 
	@-rm -f conqdriv
	$(CC) -o conqdriv $(CFLAGS) conqdriv.o $(CURDIR)/$(CONQLB) $(EXTLBS)
	@chgrp conquest conqdriv
	@chmod 2771 conqdriv

conqai: conqai.o 
	@-rm -f conqai
	$(CC) -o conqai $(CFLAGS) conqai.o $(CURDIR)/$(CONQLB) $(EXTLBS)
	@chgrp conquest conqai
	@chmod 2771 conqai

conqai.o: conqai.c c_defs.h defs.h conqdef.h conqcom.h conqcom2.h conqdata.h
	$(CC) $(CFLAGS) -c -DCONQAIMAIN conqai.c 

conqai_nomain.o: conqai.c c_defs.h defs.h conqdef.h conqcom.h conqcom2.h conqdata.h
	$(CC) $(CFLAGS) -c conqai.c
	mv conqai.o conqai_nomain.o 

conqoper: conqoper.o 
	@-rm -f conqoper
	$(CC) -o conqoper $(CFLAGS) conqoper.o $(CURDIR)/$(CONQLB) $(EXTLBS)
	@chgrp conquest conqoper
	@chmod 2771 conqoper

conqoper.o: conqoper.c c_defs.h defs.h conqdef.h conqcom.h conqcom2.h
	$(CC) $(CFLAGS) -c conqoper.c 

# we won't die if the following fails, since a default conqdata.h is supplied
conqstrat:  y.tab.o lex.yy.o
	-$(CC) -o conqstrat $(CFLAGS) lex.yy.o y.tab.o $(LIBS) $(CURDIR)/$(CONQLB) $(EXTLBS)

y.tab.c: conqstrat.c.y
	-$(YACC) -d conqstrat.c.y

y.tab.o: y.tab.c

lex.yy.c: conqstrat.c.l
	-$(LEX) conqstrat.c.l

lex.yy.o: lex.yy.c
 
# library building 
################

LBBUILD = $(CC)

$(CONQLB): conqai_nomain.o $(CONQOBJS)
	$(LBBUILD) $(LBFLAGS) conqai_nomain.o $(CONQOBJS)
	echo $(CONQLB)

# Install it!
#############################

install: all $(CONQHOME) $(CONQHOME)/etc $(CONQHOME)/bin $(CONQHOME)/lib \
	$(CONQHOME)/lib/$(CONQLB) $(BCONQUEST) $(BCONQOPER) $(BCONQDRIV)  \
	$(HCONQHELP) $(HCONQNEWS) $(CONQHOME)/lib/$(CONQLB) /opt \
	$(CONQBIN) $(CONQHOME)/etc/conqrule $(BCONQSTRAT) \
	$(CONQHOME)/etc/conquestrc 

$(CONQHOME)/lib/$(CONQLB): $(CONQLB)
	cp $(CONQLB) $(CONQHOME)/lib/$(CONQLB)
	chgrp conquest $(CONQHOME)/lib/$(CONQLB)
	chmod 644 $(CONQHOME)/lib/$(CONQLB)

$(CONQHOME):
	mkdir -p $(CONQHOME)
	chmod 775 $(CONQHOME)
	chgrp conquest $(CONQHOME)
	
$(CONQHOME)/etc:
	mkdir -p $(CONQHOME)/etc
	chmod 775 $(CONQHOME)/etc
	chgrp conquest $(CONQHOME)/etc
	
$(CONQHOME)/bin:
	mkdir -p $(CONQHOME)/bin
	chmod 775 $(CONQHOME)/bin
	chgrp conquest $(CONQHOME)/bin
	
$(CONQHOME)/lib:
	mkdir -p $(CONQHOME)/lib
	chmod 775 $(CONQHOME)/lib
	chgrp conquest $(CONQHOME)/lib
	
/opt:
	mkdir -p /opt
	chmod 775 /opt
	chgrp conquest /opt

$(CONQBIN):
	mkdir -p $(CONQBIN)
	chmod 775 $(CONQBIN)
	chgrp conquest $(CONQBIN)

$(CONQHOME)/etc/conquestrc: $(BCONQOPER)
	$(BCONQOPER) -C
	chmod 664 $(CONQHOME)/etc/conquestrc
	chgrp conquest $(CONQHOME)/etc/conquestrc

$(BCONQUEST): conquest
	@-rm -f $(BCONQUEST)
	$(CC) -o conquest $(CFLAGS) conquest.o $(CONQHOME)/lib/$(CONQLB) $(EXTLBS)
	cp conquest $(BCONQUEST)
	chgrp conquest $(BCONQUEST)
	chmod 2771 $(BCONQUEST)
	/sbin/filepriv -f plock,tshar,core $(BCONQUEST)
	@-ln -s $(BCONQUEST) $(CONQBIN)/conquest

$(BCONQOPER): conqoper
	@-rm -f $(BCONQOPER)
	$(CC) -o conqoper $(CFLAGS) conqoper.o $(CONQHOME)/lib/$(CONQLB) $(EXTLBS)
	cp conqoper $(BCONQOPER)
	chgrp conquest $(BCONQOPER)
	chmod 2771 $(BCONQOPER)
	/sbin/filepriv -f plock,tshar,core $(BCONQOPER)
	@-ln -s $(BCONQOPER) $(CONQBIN)/conqoper
	
$(BCONQDRIV): conqdriv
	@-rm -f $(BCONQDRIV)
	$(CC) -o conqdriv $(CFLAGS) conqdriv.o $(CONQHOME)/lib/$(CONQLB) $(EXTLBS)
	cp conqdriv $(BCONQDRIV)
	chgrp conquest $(BCONQDRIV)
	chmod 2771 $(BCONQDRIV)
	/sbin/filepriv -f plock,tshar,core $(BCONQDRIV)
	@-ln -s $(BCONQDRIV) $(CONQBIN)/conqdriv
	
$(BCONQAI): conqai
	@-rm -f $(BCONQAI)
	$(CC) -o conqai $(CFLAGS) conqai.o $(CONQHOME)/lib/$(CONQLB) $(EXTLBS)
	cp conqai $(BCONQAI)
	chgrp conquest $(BCONQAI)
	chmod 2771 $(BCONQAI)
	/sbin/filepriv -f plock,tshar,core $(BCONQAI)	
	@-ln -s $(BCONQAI) $(CONQBIN)/conqai

$(BCONQSTRAT): conqstrat
	@-rm -f $(BCONQSTRAT)
	-$(CC) -o conqstrat $(CFLAGS) lex.yy.o y.tab.o $(LIBS) $(CONQHOME)/lib/$(CONQLB) $(EXTLBS)
	cp conqstrat $(BCONQSTRAT)
	chgrp conquest $(BCONQSTRAT)
	chmod 755 $(BCONQSTRAT)
	@-ln -s $(BCONQSTRAT) $(CONQBIN)/conqstrat

$(CONQHOME)/etc/conqrule: conqrule
	cp conqrule $(CONQHOME)/etc/conqrule
	chgrp conquest $(CONQHOME)/etc/conqrule
	chmod 644 $(CONQHOME)/etc/conqrule

$(HCONQHELP): $(CONQHELP)
	cp $(CONQHELP) $(HCONQHELP)
	chgrp conquest $(HCONQHELP)
	chmod 644 $(HCONQHELP)

$(HCONQNEWS): $(CONQNEWS)
	cp $(CONQNEWS) $(HCONQNEWS)
	chgrp conquest $(HCONQNEWS)
	chmod 644 $(HCONQNEWS)

clean:
	rm -f *.o $(CONQUEST) $(CONQOPER) $(CONQAI) $(CONQDRIV) \
		$(CONQLB) $(CONQSTRAT) y.tab.[ch] lex.yy.[c]

depend: 
	makedepend -s "# DO NOT DELETE - MAKEDEPEND" -- *.h -- *.c >/dev/null 2>&1


# DO NOT DELETE - MAKEDEPEND

c_defs.o: config.h /usr/include/time.h /usr/include/math.h
c_defs.o: /usr/include/memory.h /usr/include/sys/ioctl.h
c_defs.o: /usr/include/sys/stat.h /usr/include/sys/types.h
c_defs.o: /usr/include/sys/time.h /usr/include/pwd.h /usr/include/grp.h
c_defs.o: defs.h
global.o: defs.h
cd2lb.o: c_defs.h config.h /usr/include/time.h /usr/include/math.h
cd2lb.o: /usr/include/memory.h /usr/include/sys/ioctl.h
cd2lb.o: /usr/include/sys/stat.h /usr/include/sys/types.h
cd2lb.o: /usr/include/sys/time.h /usr/include/pwd.h /usr/include/grp.h defs.h
cd2lb.o: conqdef.h cdcom.h conqcom2.h global.h color.h
conf.o: c_defs.h config.h /usr/include/time.h /usr/include/math.h
conf.o: /usr/include/memory.h /usr/include/sys/ioctl.h
conf.o: /usr/include/sys/stat.h /usr/include/sys/types.h
conf.o: /usr/include/sys/time.h /usr/include/pwd.h /usr/include/grp.h defs.h
conf.o: global.h conf.h
conqai.o: c_defs.h config.h /usr/include/time.h /usr/include/math.h
conqai.o: /usr/include/memory.h /usr/include/sys/ioctl.h
conqai.o: /usr/include/sys/stat.h /usr/include/sys/types.h
conqai.o: /usr/include/sys/time.h /usr/include/pwd.h /usr/include/grp.h
conqai.o: defs.h conqdef.h conqcom.h conqcom2.h global.h
conqcm.o: c_defs.h config.h /usr/include/time.h /usr/include/math.h
conqcm.o: /usr/include/memory.h /usr/include/sys/ioctl.h
conqcm.o: /usr/include/sys/stat.h /usr/include/sys/types.h
conqcm.o: /usr/include/sys/time.h /usr/include/pwd.h /usr/include/grp.h
conqcm.o: defs.h global.h conqdef.h conqcom.h conqcom2.h
conqdriv.o: c_defs.h config.h /usr/include/time.h /usr/include/math.h
conqdriv.o: /usr/include/memory.h /usr/include/sys/ioctl.h
conqdriv.o: /usr/include/sys/stat.h /usr/include/sys/types.h
conqdriv.o: /usr/include/sys/time.h /usr/include/pwd.h /usr/include/grp.h
conqdriv.o: defs.h conqdef.h conqcom.h conqcom2.h global.h
conqfig.o: c_defs.h config.h /usr/include/time.h /usr/include/math.h
conqfig.o: /usr/include/memory.h /usr/include/sys/ioctl.h
conqfig.o: /usr/include/sys/stat.h /usr/include/sys/types.h
conqfig.o: /usr/include/sys/time.h /usr/include/pwd.h /usr/include/grp.h
conqfig.o: defs.h
conqlb.o: c_defs.h config.h /usr/include/time.h /usr/include/math.h
conqlb.o: /usr/include/memory.h /usr/include/sys/ioctl.h
conqlb.o: /usr/include/sys/stat.h /usr/include/sys/types.h
conqlb.o: /usr/include/sys/time.h /usr/include/pwd.h /usr/include/grp.h
conqlb.o: defs.h conqdef.h conqcom.h conqcom2.h global.h color.h
conqmisc.o: c_defs.h config.h /usr/include/time.h /usr/include/math.h
conqmisc.o: /usr/include/memory.h /usr/include/sys/ioctl.h
conqmisc.o: /usr/include/sys/stat.h /usr/include/sys/types.h
conqmisc.o: /usr/include/sys/time.h /usr/include/pwd.h /usr/include/grp.h
conqmisc.o: defs.h conqdef.h conqcom.h conqcom2.h conqdata.h global.h color.h
conqoper.o: c_defs.h config.h /usr/include/time.h /usr/include/math.h
conqoper.o: /usr/include/memory.h /usr/include/sys/ioctl.h
conqoper.o: /usr/include/sys/stat.h /usr/include/sys/types.h
conqoper.o: /usr/include/sys/time.h /usr/include/pwd.h /usr/include/grp.h
conqoper.o: defs.h conqdef.h conqcom.h conqcom2.h global.h
conqsvr42.o: c_defs.h config.h /usr/include/time.h /usr/include/math.h
conqsvr42.o: /usr/include/memory.h /usr/include/sys/ioctl.h
conqsvr42.o: /usr/include/sys/stat.h /usr/include/sys/types.h
conqsvr42.o: /usr/include/sys/time.h /usr/include/pwd.h /usr/include/grp.h
conqsvr42.o: defs.h conqdef.h conqcom.h conqcom2.h global.h
conquest.o: c_defs.h config.h /usr/include/time.h /usr/include/math.h
conquest.o: /usr/include/memory.h /usr/include/sys/ioctl.h
conquest.o: /usr/include/sys/stat.h /usr/include/sys/types.h
conquest.o: /usr/include/sys/time.h /usr/include/pwd.h /usr/include/grp.h
conquest.o: defs.h conqdef.h conqcom.h conqcom2.h global.h
conqutil.o: c_defs.h config.h /usr/include/time.h /usr/include/math.h
conqutil.o: /usr/include/memory.h /usr/include/sys/ioctl.h
conqutil.o: /usr/include/sys/stat.h /usr/include/sys/types.h
conqutil.o: /usr/include/sys/time.h /usr/include/pwd.h /usr/include/grp.h
conqutil.o: defs.h conqdef.h conqcom.h global.h
gamlb.o: c_defs.h config.h /usr/include/time.h /usr/include/math.h
gamlb.o: /usr/include/memory.h /usr/include/sys/ioctl.h
gamlb.o: /usr/include/sys/stat.h /usr/include/sys/types.h
gamlb.o: /usr/include/sys/time.h /usr/include/pwd.h /usr/include/grp.h defs.h
global.o: c_defs.h config.h /usr/include/time.h /usr/include/math.h
global.o: /usr/include/memory.h /usr/include/sys/ioctl.h
global.o: /usr/include/sys/stat.h /usr/include/sys/types.h
global.o: /usr/include/sys/time.h /usr/include/pwd.h /usr/include/grp.h
global.o: defs.h global.h
ibuf.o: c_defs.h config.h /usr/include/time.h /usr/include/math.h
ibuf.o: /usr/include/memory.h /usr/include/sys/ioctl.h
ibuf.o: /usr/include/sys/stat.h /usr/include/sys/types.h
ibuf.o: /usr/include/sys/time.h /usr/include/pwd.h /usr/include/grp.h defs.h
ibuf.o: global.h ibuf.h
ionlb.o: c_defs.h config.h /usr/include/time.h /usr/include/math.h
ionlb.o: /usr/include/memory.h /usr/include/sys/ioctl.h
ionlb.o: /usr/include/sys/stat.h /usr/include/sys/types.h
ionlb.o: /usr/include/sys/time.h /usr/include/pwd.h /usr/include/grp.h defs.h
ionlb.o: global.h
ioplb.o: c_defs.h config.h /usr/include/time.h /usr/include/math.h
ioplb.o: /usr/include/memory.h /usr/include/sys/ioctl.h
ioplb.o: /usr/include/sys/stat.h /usr/include/sys/types.h
ioplb.o: /usr/include/sys/time.h /usr/include/pwd.h /usr/include/grp.h defs.h
ioxlb.o: c_defs.h config.h /usr/include/time.h /usr/include/math.h
ioxlb.o: /usr/include/memory.h /usr/include/sys/ioctl.h
ioxlb.o: /usr/include/sys/stat.h /usr/include/sys/types.h
ioxlb.o: /usr/include/sys/time.h /usr/include/pwd.h /usr/include/grp.h defs.h
ioxlb.o: global.h
ratfor.o: c_defs.h config.h /usr/include/time.h /usr/include/math.h
ratfor.o: /usr/include/memory.h /usr/include/sys/ioctl.h
ratfor.o: /usr/include/sys/stat.h /usr/include/sys/types.h
ratfor.o: /usr/include/sys/time.h /usr/include/pwd.h /usr/include/grp.h
ratfor.o: defs.h
rndlb.o: c_defs.h config.h /usr/include/time.h /usr/include/math.h
rndlb.o: /usr/include/memory.h /usr/include/sys/ioctl.h
rndlb.o: /usr/include/sys/stat.h /usr/include/sys/types.h
rndlb.o: /usr/include/sys/time.h /usr/include/pwd.h /usr/include/grp.h defs.h
sem.o: c_defs.h config.h /usr/include/time.h /usr/include/math.h
sem.o: /usr/include/memory.h /usr/include/sys/ioctl.h /usr/include/sys/stat.h
sem.o: /usr/include/sys/types.h /usr/include/sys/time.h /usr/include/pwd.h
sem.o: /usr/include/grp.h defs.h /usr/include/sys/ipc.h
sem.o: /usr/include/sys/ipc_f.h /usr/include/sys/sem.h
sem.o: /usr/include/sys/list.h /usr/include/sys/listasm.h
sem.o: /usr/include/sys/ksynch.h /usr/include/sys/dl.h /usr/include/sys/ipl.h
sem.o: /usr/include/sys/disp_p.h /usr/include/sys/trap.h
sem.o: /usr/include/sys/ksynch_p.h global.h conqcom.h
