#!/bin/ksh
#
# makedist - make dist/ directory and distribution
#
# Jon Trulson - 3/28/97
#
# $Id$
#
##############################################################################
# set -x

makesrcpkg
makebinpkg

VERSION=`grep ConquestVersion version.c`
VERSION=`echo $VERSION |tr -d '$;"' |cut -d' ' -f6 |tr -d " "`

CONQVER="conquest-$VERSION"

ARCFILE="${CONQVER}.src.tar.gz"
UWBINPKGFILE="${CONQVER}.pkg.tar.gz"

rm -rf dist

set -x

mkdir -p dist

cp $ARCFILE $UWBINPKGFILE dist/
cp -p conquest.txt dist/$CONQVER.txt
cp -p conquest.lsm dist/$CONQVER.lsm

chmod 644 dist/*

rm -rf $CONQVER

exit
	

