#!/bin/ksh
#
# makebinpkg - make a bin distribution
#
# Jon Trulson - 6/1/96
#
# $Id$
#
# $Log$
# Revision 1.3  1998/01/10 19:43:13  jon
# 	Minor 'adjustments' in preperation for the final release of
# 6.6.. Wish I could remember what all the changes were...
#
# Revision 1.2  1997/06/28 23:40:34  jon
# fixing dist scipts
#
# Revision 1.1.1.1  1997/05/24 19:40:45  jon
# Conquest 6.4 distribution
#
#
##############################################################################
# set -x

VERSION=`grep ConquestVersion version.c`
VERSION=`echo $VERSION |tr -d '$;"' |cut -d' ' -f6 |tr -d " "`

CONQVER="conquest-$VERSION"

ARCFILE="${CONQVER}.pkg"

rm -f ${ARCFILE}.tar.gz

echo Arcive name: $ARCFILE

CURDIR=$(pwd)

./UpdatePkginfo
rm -f ChangeLog

mkdir -p $CURDIR/pkg >/dev/null 2>&1

pkgmk -d $CURDIR/pkg -o SRCDIR="$CURDIR"
pkgtrans -s $CURDIR/pkg $CURDIR/$ARCFILE conquest

cp conquest.txt ${CONQVER}.txt

tar -cvf ${CONQVER}.pkg.tar ${ARCFILE} ${CONQVER}.txt README INSTALL

gzip -v ${CONQVER}.pkg.tar

set -x 
cp -f ${CONQVER}.pkg.tar.gz ~/tx/conquest/
chmod 644 ~/tx/conquest/${CONQVER}.pkg.tar.gz

exit
	

