#!/bin/bash
#
# makesrcpkg - make a src distribution
#
# Jon Trulson - 6/1/96
#
# $Id$
#
##############################################################################
# set -x

VERSION=`grep ConquestVersion version.c`
VERSION=`echo $VERSION |tr -d '$;"' |cut -d' ' -f6 |tr -d " "`

CONQVER="conquest-$VERSION"

ARCFILE="${CONQVER}.src.tar"

rm -f ${ARCFILE}.gz
rm -rf $CONQVER
echo Arcive name: $ARCFILE

FILELIST="ratfor.c cd2lb.c display.c iolb.c conqlb.c
	rndlb.c conqmisc.c conqutil.c conqcm.c conqsvr42.c global.c 
	ibuf.c ibuf.h version.c conf.c sem.c conquest.c conqoper.c conqdriv.c
	conqai.c c_defs.h color.h conqcom.h conqdata.h defs.h 
	conf.h conqcom2.h conqdef.h global.h color.c
	ship.h user.h planet.h team.h torp.h msg.h doomsday.h
	conquest.doc conqnews.doc configure.in configure
	config.h.in config.guess config.sub Makefile.in README 
	acconfig.h conqstrat.h conqstrat.c.l conqstrat.c.y conqrule
	LICENSE INSTALL TODO COPYRIGHT"


if [ -e CHANGES ]
then
    FILELIST="$FILELIST CHANGES"
fi

mkdir $CONQVER 2>/dev/null

cp -p $FILELIST $CONQVER/
cp -p conquest.txt $CONQVER/$CONQVER.txt
cp -p conquest.lsm $CONQVER/$CONQVER.lsm

# now the terminfo files
mkdir $CONQVER/ti
chmod 755 $CONQVER/ti
cp -p ti/*.ti $CONQVER/ti/

chmod 644 $CONQVER/ti/*

chmod 640 $CONQVER/*
chmod 755 $CONQVER/ti
chmod 750 $CONQVER/configure $CONQVER/config.guess $CONQVER/config.sub


tar cvf ${ARCFILE} $CONQVER
gzip -v $ARCFILE
rm -rf $CONQVER

set -x 
cp -f ${ARCFILE}.gz ~/tx/conquest/
chmod 644 ~/tx/conquest/${ARCFILE}.gz

exit
	

