/* Generated by conqinit on 16:34:28 02Jul06 */
/* $Id$ */


#ifndef _TEXDATA_H
#define _TEXDATA_H

static int defaultNumTextures = 142;

static cqiTextureInitRec_t defaultTextures[142] = {
 { "star", "star", 0x00000000, 0x00000000 },
 { "classm", "classm", 0x00000000, 0x00000000 },
 { "classd", "classd", 0x00000000, 0x00000000 },
 { "doomsday", "doomsday", 0x00000000, 0xffffffff },
 { "doombeam", "doombeam", 0x00000000, 0xffffffff },
 { "vbg", "vbg", 0x00000000, 0x00000000 },
 { "torp", "torp", 0x00000000, 0x00000000 },
 { "luna", "luna", 0x00000000, 0x00000000 },
 { "barrier", "barrier", 0x00000000, 0xbfc3baba },
 { "exp0", "exp0", 0x00000000, 0xffffffff },
 { "exp1", "exp1", 0x00000000, 0xffffffff },
 { "exp2", "exp2", 0x00000000, 0xffffffff },
 { "exp3", "exp3", 0x00000000, 0xffffffff },
 { "exp4", "exp4", 0x00000000, 0xffffb3cc },
 { "exp5", "exp5", 0x00000000, 0xffffb3b3 },
 { "exp6", "exp6", 0x00000000, 0xffff9980 },
 { "exp7", "exp7", 0x00000000, 0xffff9980 },
 { "exp8", "exp8", 0x00000000, 0xffff8066 },
 { "exp9", "exp9", 0x00000000, 0xffff804c },
 { "exp10", "exp10", 0x00000000, 0xffff804c },
 { "exp11", "exp11", 0x00000000, 0xffff8033 },
 { "exp12", "exp12", 0x00000000, 0xffff8019 },
 { "exp13", "exp13", 0x00000000, 0xffff8019 },
 { "exp14", "exp14", 0x00000000, 0xffff8019 },
 { "exp15", "exp15", 0x00000000, 0xffff8000 },
 { "conqlogoF", "conq-fed", 0x00000000, 0xffe6e6e6 },
 { "conqlogoR", "conq-rom", 0x00000000, 0xffe6e6e6 },
 { "conqlogoK", "conq-kli", 0x00000000, 0xffe6e6e6 },
 { "conqlogoO", "conq-ori", 0x00000000, 0xffe6e6e6 },
 { "shipFSc", "TOSfsc", 0x00000000, 0x00000000 },
 { "shipFSc-sh", "TOSf-sh", 0x00000000, 0x00000000 },
 { "shipFDe", "TOSfde", 0x00000000, 0x00000000 },
 { "shipFDe-sh", "TOSf-sh", 0x00000000, 0x00000000 },
 { "shipFCr", "TOSfcr", 0x00000000, 0x00000000 },
 { "shipFCr-sh", "TOSf-sh", 0x00000000, 0x00000000 },
 { "shipF-tac", "TOS-ftac", 0x00000000, 0x00000000 },
 { "shipF-phaser", "TOS-fph", 0x00000000, 0x00000000 },
 { "shipF-torp0", "TOS-ftorp1", 0x00000000, 0x00000000 },
 { "shipF-torp1", "TOS-ftorp2", 0x00000000, 0x00000000 },
 { "shipF-torp2", "TOS-ftorp3", 0x00000000, 0x00000000 },
 { "shipFSc-ico", "TOS-fico_s", 0x00000000, 0x00000000 },
 { "shipFDe-ico", "TOS-fico", 0x00000000, 0x00000000 },
 { "shipFCr-ico", "TOS-fico_c", 0x00000000, 0x00000000 },
 { "shipFSc-ico-sh", "TOS-fish_s", 0x00000000, 0x00000000 },
 { "shipFDe-ico-sh", "TOS-fish", 0x00000000, 0x00000000 },
 { "shipFCr-ico-sh", "TOS-fish_c", 0x00000000, 0x00000000 },
 { "shipF-ico-decal1", "hud-decal1", 0x00000000, 0x00000000 },
 { "shipF-ico-decal2", "hud-decal2", 0x00000000, 0x00000000 },
 { "shipF-dial", "TOS-fihd", 0x00000000, 0x00000000 },
 { "shipF-dialp", "TOS-fihp", 0x00000000, 0x00000000 },
 { "shipF-warp", "TOS-fwarp", 0x00000000, 0x00000000 },
 { "shipF-warp-col", "", 0x00000001, 0xffd72d00 },
 { "shipF-ico-cloak", "ico-cloak", 0x00000000, 0x00000000 },
 { "shipF-ico-shcrit", "ico-shcrit", 0x00000000, 0x00000000 },
 { "shipF-ico-engcrit", "ico-engcrit", 0x00000000, 0x00000000 },
 { "shipF-ico-wepcrit", "ico-wepcrit", 0x00000000, 0x00000000 },
 { "shipF-ico-hulcrit", "ico-hulcrit", 0x00000000, 0x00000000 },
 { "shipF-ico-repair", "ico-repair", 0x00000000, 0x00000000 },
 { "shipRSc", "TOSrsc", 0x00000000, 0x00000000 },
 { "shipRSc-sh", "TOSr-sh", 0x00000000, 0x00000000 },
 { "shipRDe", "TOSrde", 0x00000000, 0x00000000 },
 { "shipRDe-sh", "TOSr-sh", 0x00000000, 0x00000000 },
 { "shipRCr", "TOSrcr", 0x00000000, 0x00000000 },
 { "shipRCr-sh", "TOSr-sh", 0x00000000, 0x00000000 },
 { "shipR-tac", "TOS-rtac", 0x00000000, 0x00000000 },
 { "shipR-phaser", "TOS-rph", 0x00000000, 0x00000000 },
 { "shipR-torp0", "TOS-rtorp1", 0x00000000, 0x00000000 },
 { "shipR-torp1", "TOS-rtorp3", 0x00000000, 0x00000000 },
 { "shipR-torp2", "TOS-rtorp3", 0x00000000, 0x00000000 },
 { "shipRSc-ico", "TOS-rico_s", 0x00000000, 0x00000000 },
 { "shipRDe-ico", "TOS-rico", 0x00000000, 0x00000000 },
 { "shipRCr-ico", "TOS-rico_c", 0x00000000, 0x00000000 },
 { "shipRSc-ico-sh", "TOS-rish_s", 0x00000000, 0x00000000 },
 { "shipRDe-ico-sh", "TOS-rish", 0x00000000, 0x00000000 },
 { "shipRCr-ico-sh", "TOS-rish_c", 0x00000000, 0x00000000 },
 { "shipR-ico-decal1", "hud-decal1", 0x00000000, 0x00000000 },
 { "shipR-ico-decal2", "hud-decal2", 0x00000000, 0x00000000 },
 { "shipR-dial", "TOS-rihd", 0x00000000, 0x00000000 },
 { "shipR-dialp", "TOS-rihp", 0x00000000, 0x00000000 },
 { "shipR-warp", "TOS-rwarp", 0x00000000, 0x00000000 },
 { "shipR-warp-col", "", 0x00000001, 0xffbfbcbc },
 { "shipR-ico-cloak", "ico-cloak", 0x00000000, 0x00000000 },
 { "shipR-ico-shcrit", "ico-shcrit", 0x00000000, 0x00000000 },
 { "shipR-ico-engcrit", "ico-engcrit", 0x00000000, 0x00000000 },
 { "shipR-ico-wepcrit", "ico-wepcrit", 0x00000000, 0x00000000 },
 { "shipR-ico-hulcrit", "ico-hulcrit", 0x00000000, 0x00000000 },
 { "shipR-ico-repair", "ico-repair", 0x00000000, 0x00000000 },
 { "shipKSc", "TOSksc", 0x00000000, 0x00000000 },
 { "shipKSc-sh", "TOSk-sh", 0x00000000, 0x00000000 },
 { "shipKDe", "TOSkde", 0x00000000, 0x00000000 },
 { "shipKDe-sh", "TOSk-sh", 0x00000000, 0x00000000 },
 { "shipKCr", "TOSkcr", 0x00000000, 0x00000000 },
 { "shipKCr-sh", "TOSk-sh", 0x00000000, 0x00000000 },
 { "shipK-tac", "TOS-ktac", 0x00000000, 0x00000000 },
 { "shipK-phaser", "TOS-kph", 0x00000000, 0x00000000 },
 { "shipK-torp0", "TOS-ktorp1", 0x00000000, 0x00000000 },
 { "shipK-torp1", "TOS-ktorp2", 0x00000000, 0x00000000 },
 { "shipK-torp2", "TOS-ktorp3", 0x00000000, 0x00000000 },
 { "shipKSc-ico", "TOS-kico_s", 0x00000000, 0x00000000 },
 { "shipKDe-ico", "TOS-kico", 0x00000000, 0x00000000 },
 { "shipKCr-ico", "TOS-kico_c", 0x00000000, 0x00000000 },
 { "shipKSc-ico-sh", "TOS-kish_s", 0x00000000, 0x00000000 },
 { "shipKDe-ico-sh", "TOS-kish", 0x00000000, 0x00000000 },
 { "shipKCr-ico-sh", "TOS-kish_c", 0x00000000, 0x00000000 },
 { "shipK-ico-decal1", "hud-decal1", 0x00000000, 0x00000000 },
 { "shipK-ico-decal2", "hud-decal2", 0x00000000, 0x00000000 },
 { "shipK-dial", "TOS-kihd", 0x00000000, 0x00000000 },
 { "shipK-dialp", "TOS-kihp", 0x00000000, 0x00000000 },
 { "shipK-warp", "TOS-kwarp", 0x00000000, 0x00000000 },
 { "shipK-warp-col", "", 0x00000001, 0xffd72d00 },
 { "shipK-ico-cloak", "ico-cloak", 0x00000000, 0x00000000 },
 { "shipK-ico-shcrit", "ico-shcrit", 0x00000000, 0x00000000 },
 { "shipK-ico-engcrit", "ico-engcrit", 0x00000000, 0x00000000 },
 { "shipK-ico-wepcrit", "ico-wepcrit", 0x00000000, 0x00000000 },
 { "shipK-ico-hulcrit", "ico-hulcrit", 0x00000000, 0x00000000 },
 { "shipK-ico-repair", "ico-repair", 0x00000000, 0x00000000 },
 { "shipOSc", "TOSosc", 0x00000000, 0x00000000 },
 { "shipOSc-sh", "TOSr-sh", 0x00000000, 0x00000000 },
 { "shipODe", "TOSode", 0x00000000, 0x00000000 },
 { "shipODe-sh", "TOSf-sh", 0x00000000, 0x00000000 },
 { "shipOCr", "TOSocr", 0x00000000, 0x00000000 },
 { "shipOCr-sh", "TOSf-sh", 0x00000000, 0x00000000 },
 { "shipO-tac", "TOS-otac", 0x00000000, 0x00000000 },
 { "shipO-phaser", "phaser", 0x00000000, 0x00000000 },
 { "shipOSc-ico", "TOS-oico_s", 0x00000000, 0x00000000 },
 { "shipODe-ico", "TOS-oico", 0x00000000, 0x00000000 },
 { "shipOCr-ico", "TOS-oico_c", 0x00000000, 0x00000000 },
 { "shipOSc-ico-sh", "TOS-oish_s", 0x00000000, 0x00000000 },
 { "shipODe-ico-sh", "TOS-oish", 0x00000000, 0x00000000 },
 { "shipOCr-ico-sh", "TOS-oish_c", 0x00000000, 0x00000000 },
 { "shipO-ico-decal1", "hud-decal1", 0x00000000, 0x00000000 },
 { "shipO-ico-decal2", "hud-decal2", 0x00000000, 0x00000000 },
 { "shipO-dial", "TOS-oihd", 0x00000000, 0x00000000 },
 { "shipO-dialp", "TOS-oihp", 0x00000000, 0x00000000 },
 { "shipO-warp", "TOS-owarp", 0x00000000, 0x00000000 },
 { "shipO-warp-col", "", 0x00000001, 0xff9fefff },
 { "shipO-ico-cloak", "ico-cloak", 0x00000000, 0x00000000 },
 { "shipO-ico-shcrit", "ico-shcrit", 0x00000000, 0x00000000 },
 { "shipO-ico-engcrit", "ico-engcrit", 0x00000000, 0x00000000 },
 { "shipO-ico-wepcrit", "ico-wepcrit", 0x00000000, 0x00000000 },
 { "shipO-ico-hulcrit", "ico-hulcrit", 0x00000000, 0x00000000 },
 { "shipO-ico-repair", "ico-repair", 0x00000000, 0x00000000 },
};

static int defaultNumAnimations = 11;

static cqiAnimationInitRec_t defaultAnimations[11] = {
 { "explosion", "explode", 7 },
 { "bombing", "bomb", 9 },
 { "onesec", "onesec", 0 },
 { "halfsec", "halfsec", 1 },
 { "qtrsec", "qtrsec", 2 },
 { "shipK-torp", "shipK-torp", 3 },
 { "shipO-torp", "shipO-torp", 6 },
 { "shipF-torp", "shipF-torp", 4 },
 { "shipR-torp", "shipR-torp", 5 },
 { "doomsday-ap-fire", "doomsday-ap-fire", 8 },
 { "overload-pulse", "pulse", 10 },
};

static int defaultNumAnimDefs = 11;

static cqiAnimDefInitRec_t defaultAnimDefs[11] = {
 { 
   "onesec",
   "",
   0,
   0x00000008,
   0x00000000, /* istate */
   "",
   0x00000000,
   0.000000,
   0.000000,
   { /* texanim */
     0x00000000,
     0,
     0,
     0,
     0
   },
   { /* colanim */
     0x00000000,
     0,
     0,
     0,
     0,
     0.000000,
     0.000000,
     0.000000,
     0.000000
   },
   { /* geoanim */
     0,
     0,
     0,
     0,
     0.000000,
     0.000000,
     0.000000,
     0.000000,
     0.000000
   },
   { /* toganim */
     1000
   },
 },
 { 
   "halfsec",
   "",
   0,
   0x00000008,
   0x00000000, /* istate */
   "",
   0x00000000,
   0.000000,
   0.000000,
   { /* texanim */
     0x00000000,
     0,
     0,
     0,
     0
   },
   { /* colanim */
     0x00000000,
     0,
     0,
     0,
     0,
     0.000000,
     0.000000,
     0.000000,
     0.000000
   },
   { /* geoanim */
     0,
     0,
     0,
     0,
     0.000000,
     0.000000,
     0.000000,
     0.000000,
     0.000000
   },
   { /* toganim */
     500
   },
 },
 { 
   "qtrsec",
   "",
   0,
   0x00000008,
   0x00000000, /* istate */
   "",
   0x00000000,
   0.000000,
   0.000000,
   { /* texanim */
     0x00000000,
     0,
     0,
     0,
     0
   },
   { /* colanim */
     0x00000000,
     0,
     0,
     0,
     0,
     0.000000,
     0.000000,
     0.000000,
     0.000000
   },
   { /* geoanim */
     0,
     0,
     0,
     0,
     0.000000,
     0.000000,
     0.000000,
     0.000000,
     0.000000
   },
   { /* toganim */
     250
   },
 },
 { 
   "shipK-torp",
   "shipK-torp",
   0,
   0x00000001,
   0x00000004, /* istate */
   "",
   0x00000000,
   0.000000,
   180.000000,
   { /* texanim */
     0x00000000,
     3,
     50,
     0,
     0
   },
   { /* colanim */
     0x00000000,
     0,
     0,
     0,
     0,
     0.000000,
     0.000000,
     0.000000,
     0.000000
   },
   { /* geoanim */
     0,
     0,
     0,
     0,
     0.000000,
     0.000000,
     0.000000,
     0.000000,
     0.000000
   },
   { /* toganim */
     0
   },
 },
 { 
   "shipF-torp",
   "shipF-torp",
   0,
   0x00000001,
   0x00000004, /* istate */
   "",
   0x00000000,
   0.000000,
   120.000000,
   { /* texanim */
     0x00000000,
     3,
     100,
     0,
     0
   },
   { /* colanim */
     0x00000000,
     0,
     0,
     0,
     0,
     0.000000,
     0.000000,
     0.000000,
     0.000000
   },
   { /* geoanim */
     0,
     0,
     0,
     0,
     0.000000,
     0.000000,
     0.000000,
     0.000000,
     0.000000
   },
   { /* toganim */
     0
   },
 },
 { 
   "shipR-torp",
   "shipR-torp",
   0,
   0x00000001,
   0x00000004, /* istate */
   "",
   0x00000000,
   0.000000,
   110.000000,
   { /* texanim */
     0x00000000,
     3,
     100,
     0,
     0
   },
   { /* colanim */
     0x00000000,
     0,
     0,
     0,
     0,
     0.000000,
     0.000000,
     0.000000,
     0.000000
   },
   { /* geoanim */
     0,
     0,
     0,
     0,
     0.000000,
     0.000000,
     0.000000,
     0.000000,
     0.000000
   },
   { /* toganim */
     0
   },
 },
 { 
   "shipO-torp",
   "torp",
   0,
   0x00000004,
   0x0000000c, /* istate */
   "",
   0x00000000,
   -1.000000,
   110.000000,
   { /* texanim */
     0x00000000,
     0,
     0,
     0,
     0
   },
   { /* colanim */
     0x00000000,
     0,
     0,
     0,
     0,
     0.000000,
     0.000000,
     0.000000,
     0.000000
   },
   { /* geoanim */
     0,
     70,
     0,
     0,
     0.000000,
     0.000000,
     0.000000,
     0.000000,
     0.000000
   },
   { /* toganim */
     0
   },
 },
 { 
   "explode",
   "exp",
   0,
   0x00000007,
   0x00000004, /* istate */
   "",
   0x00000000,
   0.000000,
   450.000000,
   { /* texanim */
     0x00000000,
     16,
     100,
     1,
     0
   },
   { /* colanim */
     0x00000000,
     10,
     80,
     1,
     0,
     -0.100000,
     0.000000,
     -0.001000,
     -0.010000
   },
   { /* geoanim */
     10,
     100,
     1,
     0,
     0.000000,
     0.000000,
     0.000000,
     0.000000,
     10.000000
   },
   { /* toganim */
     0
   },
 },
 { 
   "doomsday-ap-fire",
   "",
   0,
   0x00000008,
   0x00000000, /* istate */
   "",
   0x00000000,
   0.000000,
   0.000000,
   { /* texanim */
     0x00000000,
     0,
     0,
     0,
     0
   },
   { /* colanim */
     0x00000000,
     0,
     0,
     0,
     0,
     0.000000,
     0.000000,
     0.000000,
     0.000000
   },
   { /* geoanim */
     0,
     0,
     0,
     0,
     0.000000,
     0.000000,
     0.000000,
     0.000000,
     0.000000
   },
   { /* toganim */
     700
   },
 },
 { 
   "bomb",
   "exp",
   0,
   0x00000003,
   0x00000004, /* istate */
   "",
   0x00000000,
   0.000000,
   100.000000,
   { /* texanim */
     0x00000000,
     16,
     40,
     1,
     0
   },
   { /* colanim */
     0x00000000,
     10,
     20,
     1,
     0,
     -0.100000,
     0.000000,
     -0.001000,
     -0.010000
   },
   { /* geoanim */
     0,
     0,
     0,
     0,
     0.000000,
     0.000000,
     0.000000,
     0.000000,
     0.000000
   },
   { /* toganim */
     0
   },
 },
 { 
   "pulse",
   "",
   0,
   0x00000002,
   0x00000002, /* istate */
   "",
   0x9fff0000,
   0.000000,
   0.000000,
   { /* texanim */
     0x00000000,
     0,
     0,
     0,
     0
   },
   { /* colanim */
     0x00000000,
     20,
     50,
     1,
     0,
     -0.015000,
     0.000000,
     0.000000,
     0.000000
   },
   { /* geoanim */
     0,
     0,
     0,
     0,
     0.000000,
     0.000000,
     0.000000,
     0.000000,
     0.000000
   },
   { /* toganim */
     0
   },
 },
};

#endif /* _TEXDATA_H */

