#!/bin/ksh
#
# UpdatePkginfo - strips version number info from version.c and update
#		  some of the fields in the pkginfo file
#
# Jon Trulson - 4/13/96
#
# $Id$
#
# $Log$
# Revision 1.2  1997/06/28 23:40:31  jon
# fixing dist scipts
#
# Revision 1.1.1.1  1996/04/28 07:02:43  jon
# Conquest 6.4 distribution
#
# Revision 1.2  1996/04/28  07:02:29  jon
# - cleans up after itself now.
#
# Revision 1.1  1996/04/22  23:30:19  jon
# Initial revision
#
#
#
############################################################################

grep -v PSTAMP pkginfo |grep -v IDENT |grep -v VERSION >/tmp/version.$$

cp /tmp/version.$$ pkginfo

IDENT=`grep ConquestVersion version.c`
IDENT=`echo $IDENT |tr -d '$;"' |cut -d' ' -f6 |tr -d " "`

echo IDENT = $IDENT
echo "IDENT=$IDENT" >>pkginfo

echo VERSION = $IDENT
echo "VERSION=$IDENT" >>pkginfo

/bin/rm /tmp/version.$$
exit


